language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
install: bundle install
#whitelist
branches:
  only:
    - master
    - develop
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
before_script:
  - psql -c 'create database ruby_getting_started_test' -U postgres
